# Generated by Django 3.1.6 on 2021-02-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210217_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ranking',
        ),
    ]
